---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kubetoy-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kubetoy
  labels:
    app: kubetoy
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: kubetoy
    spec:
      containers:
      - name: kubetoy
        image: icpcoc/kubetoy:1.0.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
        volumeMounts:
        - name: datavol
          mountPath: /var/test
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 5
      volumes:
      - name: datavol
        persistentVolumeClaim:
          claimName: kubetoy-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: kubetoy
  labels:
    app: kubetoy
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      name: kubetoy
  selector:
    app: kubetoy