---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kubetoy-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kubetoy
  labels:
    app: kubetoy
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: kubetoy
    spec:
      containers:
      - name: kubetoy
        image: ibmicpcoc/kubetoy:1.4.0
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        volumeMounts:
        - name: datavol
          mountPath: /var/test
        - name: configvol
          mountPath: /var/config
        - name: secretvol
          mountPath: /var/secret
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 5
        env:
        - name: ENV_TOY_CONFIGMAP
          valueFrom: 
            configMapKeyRef:
              name: kubetoy-configmap-env
              key: ENV_TOY_CONFIGMAP
        - name: ENV_TOY_SECRET
          valueFrom:
            secretKeyRef:
              name: kubetoy-secret-env
              key: ENV_TOY_SECRET
      volumes:
      - name: datavol
        persistentVolumeClaim:
          claimName: kubetoy-pvc
      - name: configvol
        configMap:
          name: kubetoy-configmap-files
      - name: secretvol
        secret:
          secretName: kubetoy-secret-files
---
apiVersion: v1
kind: Service
metadata:
  name: kubetoy
  labels:
    app: kubetoy
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      name: kubetoy
  selector:
    app: kubetoy
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: kubetoy-configmap-env
data:
  ENV_TOY_CONFIGMAP: 'This is a configuration value.'
---
apiVersion: v1
kind: Secret
metadata:
  name: kubetoy-secret-env
type: Opaque
data:
  ENV_TOY_SECRET: VGhpcyBpcyBhIHRlc3Q=
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: kubetoy-configmap-files
data:
  config-file:  '{ "default": "123" }'
---
apiVersion: v1
kind: Secret
metadata:
  name: kubetoy-secret-files
type: Opaque
data:
  toy-secret: U2hoLi4uIFRoaXMgaXMgYSBzZWNyZXQu

  